
base_url = "http://127.0.0.1:1111/"
title = "Miles Yeh"
description = "chill site"
theme = "anemone"
compile_sass = false
minify_html = true
generate_feeds = false
default_language = "en"


[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"


[link_checker]
internal_level = "warn"



[extra]
socials = [
  # Configure socials here
]

header_nav = [
  { url = "/", name_en = "/home/"},
  #{ url = "/about", name_en = "/about/"},
  { url = "/projects", name_en = "/projects/"},
  { url = "/writings", name_en = "/writings/"}
]

theme = "dark"
default_theme = "dark"
list_pages = false
author = "miles"
display_author = true
latex = true
twitter_card = false

